export default {
  waitlist_title: "Join the Waitlist",
  waitlist_desc:
    "Help protect rainforests while earning rewards. Join our waitlist for exclusive access to our platform!",
  submit: "Submit",
  waitlist_form_placeholder: "Enter wallet address",
  toast_invalid_address: "Enter Valid Address",
  toast_already_whitelisted: "Address Already Whitelisted",
  toast_added_to_whitelist: "Address Added to Whitelist",
  hero_title: "Forest preservation verified by Cryptographic Truth",
  hero_desc:
    "Join the Rainforest Proof-Of-Conversation project: obtain blockchain-validated proof of the carbon dioxide absorption of your rainforest tracked in real time by satellites.",
  hero_button: "Join the Waitlist",
  home_pre_title_2: "Steps Towards Conservation",
  home_title_2: "Why Rainforest Proof-Of-Conservation matters?",
  home_problem_title: "The Problem",
  home_problem_desc:
    "The voluntary carbon market is flooded with trust-based, intransparent, and illiquid carbon offsets that cannot be easily verified and traded. Many certificates even turn out to be not backed by data.",
  home_solution_title: "The Solution",
  home_solution_desc:
    "Rainforest Proof-of-Conservation enables direct and immediate audits for everyone by storing real-time satellite observations of forest cover in a tamper-proof, validated, and transparent way in the blockchain. ",
  home_pre_title_3: "TRUSTED BY LEADING BRANDS AROUND THE WORLD",
  accordian_title_1: "What is the RaCoTo project?",
  accordian_desc_1:
    "A project that rewards rainforest owners with tokens for preserving their land, helping fight climate change and protect biodiversity.",
  accordian_title_2: "What are RaCoTo tokens?",
  accordian_desc_2:
    "Tokens representing one ton of fixed carbon dioxide, given to registered rainforest owners for conservation efforts.",
  accordian_title_3: "How are RaCoTos earned? ",
  accordian_desc_3:
    "By registering your rainforest with the project and preserving it, you'll receive RaCoTo tokens based on real-time satellite monitoring.",
  accordian_title_4: "Why are RaCoTos more transparent?",
  accordian_desc_4:
    "They rely on public, tamper-proof blockchain and independent satellite data, ensuring superior integrity and transparency compared to other offsets.",
  accordian_title_5: "How are RaCoTos different from other carbon offsets?",
  accordian_desc_5:
    "RaCoTos are the only carbon offsets that are based on real-time satellite monitoring, ensuring superior integrity and transparency compared to other offsets.",
  accordian_title_6: "How to sell RaCoTo tokens?",
  accordian_desc_6:
    "You can sell RaCoTo tokens to carbon dioxide emitters or hold onto them until they gain more value.",
  accordian_title_7: "How to get started?",
  accordian_desc_7:
    "Register your rainforest with the project and start earning RaCoTo tokens.",
  accordian_title_8: "How to learn more about RaCoTo?",
  accordian_desc_8:
    "Read the project's lite paper or white paper or get in touch with the team for more information.",
  home_faq_title: "Frequently Asked Questions",
  home_faq_pre_title: "LEARN MORE ABOUT RACOTO",
  home_project_pre_title: "JOIN THE NET ZERO MOVEMENT",
  home_project_title: "Explore our Proof-Of-Preservation projects",
  home_procedure_title: "Data powering carbon offsets with trustless integrity",
  home_procedure_pre_title: "HOW IT WORKS",
  register_title: "Register your rainforest",
  register_input_wallet: "Wallet Address",
  register_input_wallet_placeholder: "Enter wallet address",
  register_input_username: "Owner Name",
  register_input_username_placeholder: "Enter Rainforest owner name",
  register_input_land_image: "Land Image",
  register_input_land_image_placeholder: "Click to upload land images",
  register_input_certificate: "Certificates",
  register_input_ownership_certificate_placeholder: "Ownership Certificate",
  register_input_boundary_certificate_placeholder: "Boundary Certificate",
  register_reset_btn: "Reset",
  register_submit_btn: "Register",
  register_terms:
    " I agree that I am not using my rainforest with any carbon offsetting program.",
  procedure_title_1: "Registration",
  procedure_desc_1:
    "Rainforest owners register to receive Rainforest Conservation Tokens (RCTs) for preserving biodiversity and reducing carbon emissions.",
  procedure_title_2: "Proof",
  procedure_desc_2:
    "Owners deposit thier land ownership certificates at an independent custodian, enabling third-party real-time audit via an interface.",
  procedure_title_3: "Validation",
  procedure_desc_3:
    "RCT validation ensures each token represents one ton of carbon dioxide, considering satellite images and custodian-provided proof of ownership.",
  procedure_title_4: "Payout",
  procedure_desc_4:
    "Token payout is triggered by successful RCT validation of ownership and rainforest cover, enabling owners to sell on the carbon market.",
  navbar_login: "Login",
  navbar_register: "Register",
  login_modal_title: "Connect Wallet",
  login_modal_desc: "Connect Wallet to get started",
  connect_wallet_btn: "Connect Wallet",
  wrong_network_btn: "Wrong Network",
  admin_login_title: "Proof-Of-Ownership Console",
  admin_wallet_placeholder: "Rainforest owner wallet",
  admin_password_placeholder: "Enter password",
  admin_boundary_placeholder: "Rainforest GeoStore ID",
  admin_submit: "Submit",
  admin_nav_accept: "Approve",
  admin_nav_reject: "Decline",
  admin_accept_app_title: "Approve Proof-Of-Ownership",
  admin_reject_app_title: "Decline Proof-Of-Ownership",
  nav_home: "Home",
  nav_synopsis: "Synopsis",
  nav_procedure: "Proof-Of-conversation",
  nav_users: "RaCoTo Users",
  nav_faq: "FAQ",
  user_earnings: "Your Earnings",
  user_withdraw: "Withdraw",
  user_nav_project: "My Project",
  user_nav_earnings: "My Earnings",
  user_nav_support: "Support",
};
